## Numpy Basic Operations

In [2]:
import numpy as np

In [3]:
myList=[21,22,23]
myList

[21, 22, 23]

In [4]:
type(myList)

list

In [5]:
arr=np.array(myList)
arr

array([21, 22, 23])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim

1

In [8]:
arr[1]

22

In [9]:
arr2=np.array([(21,22,23),(24,25,26)])
arr2

array([[21, 22, 23],
       [24, 25, 26]])

In [10]:
arr2.ndim

2

In [11]:
list_mul=myList*2
list_mul

[21, 22, 23, 21, 22, 23]

In [12]:
arr_mul=arr*2
arr_mul

array([42, 44, 46])

In [13]:
a=53/2
a

26.5

In [14]:
a=53//2
a

26

In [15]:
arr2.size

6

In [16]:
arr2.itemsize

4

In [17]:
arr2.dtype

dtype('int32')

In [19]:
arr2.shape

(2, 3)

In [20]:
arr2.reshape(3,2)

array([[21, 22],
       [23, 24],
       [25, 26]])

In [21]:
arr2

array([[21, 22, 23],
       [24, 25, 26]])

In [23]:
arr2.T

array([[21, 24],
       [22, 25],
       [23, 26]])

In [24]:
arr2[1,2]

26

In [25]:
arr2[0:,2]

array([23, 26])

In [26]:
arr2[0:1,2]

array([23])

In [28]:
n_arr=np.array([[[(1,2),(3,4),(5,6),(7,8)]]])
print(n_arr)

[[[[1 2]
   [3 4]
   [5 6]
   [7 8]]]]


In [31]:
n_arr.ndim

4

In [32]:
n_arr[0,0,1:,1]

array([4, 6, 8])

In [33]:
myLin=np.linspace(0,1,10)
myLin

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [34]:
arr2.min()

21

In [35]:
arr2.max()

26

In [36]:
arr2.sum()

141

In [37]:
#sum on basis of axis
arr2.sum(axis=0)
arr2.sum(axis=1)

array([66, 75])

In [38]:
arr2.sum(axis=1)

array([66, 75])

In [39]:
arr2.sum(axis=0)

array([45, 47, 49])

In [40]:
np.sqrt(arr2)

array([[4.58257569, 4.69041576, 4.79583152],
       [4.89897949, 5.        , 5.09901951]])

In [41]:
arr2**2

array([[441, 484, 529],
       [576, 625, 676]], dtype=int32)

In [42]:
arr1=np.array([(1,2,3),(4,5,6)])
arr2=np.array([(1,2,3),(4,5,6)])
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [43]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [46]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [3]:
import numpy as np
a=np.array([(1,2),(3,4),(5,6),(7,8)])
a[0:2,1]

array([2, 4])

In [8]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, start=0, /)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [5]:
help(np.array)


Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}